version: '3'
services:
  client:
    build: ./client
    ports:
      - "4000:80"
    depends_on: 
      - server
  server:
    build: ./server
    environment: 
      PORT: 8080
      DB_USER: admin
      DB_PASSWORD: postgres
      DB_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:10.7-alpine
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "4444:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: foo@mail.com
      PGADMIN_DEFAULT_PASSWORD: StrongPassword1
    
