version: '3'
services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on: 
      - server
  server:
    build: ./server
    environment: 
      PORT: 8080
      DB_USER: admin
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:10.7-alpine
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
